/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as collectionFactorySol from "./Collection-factory.sol";
export type { collectionFactorySol };
export type { Collection } from "./Collection";
